export const chatContent = [
  {
    image: "/image/avator/image-1.jpg",
    title: "Alice",
    date: "03:15 PM",
    messages: "7",
    active: true,
  },
  {
    image: "/image/avator/image-2.jpg",
    title: "Bob",
    date: "08:45 AM",
    active: false,
  },
  {
    image: "/image/avator/image-3.jpg",
    title: "Charlie",
    date: "12:30 PM",
    messages: "15",
    active: true,
  },
  {
    image: "/image/avator/image-4.jpg",
    title: "Diana",
    date: "04:20 PM",
    active: false,
  },
  {
    image: "/image/avator/image-1.jpg",
    title: "Eve",
    date: "01:10 PM",
    messages: "5",
    active: true,
  },
  {
    image: "/image/avator/image-2.jpg",
    title: "Frank",
    date: "09:50 AM",
    active: false,
  },
  {
    image: "/image/avator/image-3.jpg",
    title: "Grace",
    date: "11:55 AM",
    messages: "10",
    active: true,
  },
  {
    image: "/image/avator/image-1.jpg",
    title: "Hank",
    date: "07:30 AM",
    active: false,
  },
  {
    image: "/image/avator/image-2.jpg",
    title: "Ivy",
    date: "02:00 PM",
    messages: "20",
    active: true,
  },
  {
    image: "/image/avator/image-3.jpg",
    title: "Jack",
    date: "05:45 PM",
    active: false,
  },
  {
    image: "/image/avator/image-4.jpg",
    title: "Karen",
    date: "10:20 AM",
    messages: "3",
    active: true,
  },
  {
    image: "/image/avator/image-1.jpg",
    title: "Leo",
    date: "06:10 PM",
    active: false,
  },
];

export const contactContent = [
  {
    image: "/image/avator/image-1.jpg",
    title: "Alice",
    lastSeen: "Last seen 5 days ago",
    active: true,
  },
  {
    image: "/image/avator/image-2.jpg",
    title: "Bob",
    lastSeen: " is busy now",
    active: false,
  },
  {
    image: "/image/avator/image-3.jpg",
    title: "Charlie",
    lastSeen: "is online now",
    active: true,
  },
  {
    image: "/image/avator/image-4.jpg",
    title: "Diana",
    lastSeen: "Last seen a week ago",
    active: true,
  },
  {
    image: "/image/avator/image-1.jpg",
    title: "Eve",
    lastSeen: "11:15 AM",
    active: false,
  },
  {
    image: "/image/avator/image-2.jpg",
    title: "Frank",
    lastSeen: "Last seen 10 min ago",
    active: false,
  },
  {
    image: "/image/avator/image-3.jpg",
    title: "Grace",
    lastSeen: "09:30 AM",
    active: true,
  },
  {
    image: "/image/avator/image-4.jpg",
    title: "Hank",
    lastSeen: "08:00 AM",
    active: false,
  },
  {
    image: "/image/avator/image-1.jpg",
    title: "Ivy",
    lastSeen: "07:15 AM",
    active: true,
  },
  {
    image: "/image/avator/image-2.jpg",
    title: "Jack",
    lastSeen: "06:45 AM",
    active: true,
  },
];

export const groupContent = [
  {
    image: "/image/avator/image-1.jpg",
    title: "Developers Group",
    date: "03:15 PM",
    messages: "100",
    active: true,
  },
  {
    image: "/image/avator/image-2.jpg",
    title: "Designers Circle",
    date: "08:45 AM",
    active: false,
  },
  {
    image: "/image/avator/image-3.jpg",
    title: "Marketing Team",
    date: "12:30 PM",
    messages: "50",
    active: true,
  },
  {
    image: "/image/avator/image-4.jpg",
    title: "Project Managers",
    date: "04:20 PM",
    active: false,
  },
  {
    image: "/image/avator/image-1.jpg",
    title: "Product Owners",
    date: "01:10 PM",
    messages: "5",
    active: true,
  },
  {
    image: "/image/avator/image-2.jpg",
    title: "Support Team",
    date: "09:50 AM",
    active: false,
  },
  {
    image: "/image/avator/image-3.jpg",
    title: "Sales Department",
    date: "11:55 AM",
    messages: "10",
    active: true,
  },
  {
    image: "/image/avator/image-1.jpg",
    title: "Quality Assurance",
    date: "07:30 AM",
    active: false,
  },
  {
    image: "/image/avator/image-2.jpg",
    title: "Content Creators",
    date: "02:00 PM",
    messages: "20",
    active: true,
  },
  {
    image: "/image/avator/image-3.jpg",
    title: "Finance Team",
    date: "05:45 PM",
    active: false,
  },
  {
    image: "/image/avator/image-4.jpg",
    title: "Operations Group",
    date: "10:20 AM",
    messages: "3",
    active: true,
  },
  {
    image: "/image/avator/image-1.jpg",
    title: "Human Resources",
    date: "06:10 PM",
    active: false,
  },
];

export const callContent = [
  {
    image: "/image/avator/image-1.jpg",
    title: "Alice",
    callDuration: "60 Min Ago",
    callStatus: "Received",
    callTime: "03:15 PM",
  },
  {
    image: "/image/avator/image-2.jpg",
    title: "Bob",
    callDuration: "50 Min Ago",
    callStatus: "Missed",
    callTime: "08:45 AM",
  },
  {
    image: "/image/avator/image-3.jpg",
    title: "Charlie",
    callDuration: "30 Min Ago",
    callStatus: "Received",
    callTime: "12:30 PM",
  },
  {
    image: "/image/avator/image-4.jpg",
    title: "Diana",
    callDuration: "15 Min Ago",
    callStatus: "Received",
    callTime: "04:20 PM",
  },
  {
    image: "/image/avator/image-1.jpg",
    title: "Eve",
    callDuration: "45 Min Ago",
    callStatus: "Missed",
    callTime: "01:10 PM",
  },
  {
    image: "/image/avator/image-2.jpg",
    title: "Frank",
    callDuration: "20 Min Ago",
    callStatus: "Received",
    callTime: "09:50 AM",
  },
  {
    image: "/image/avator/image-3.jpg",
    title: "Grace",
    callDuration: "25 Min Ago",
    callStatus: "Received",
    callTime: "11:55 AM",
  },
  {
    image: "/image/avator/image-4.jpg",
    title: "Hank",
    callDuration: "10 Min Ago",
    callStatus: "Missed",
    callTime: "07:30 AM",
  },
  {
    image: "/image/avator/image-1.jpg",
    title: "Ivy",
    callDuration: "5 Min Ago",
    callStatus: "Received",
    callTime: "02:00 PM",
  },
  {
    image: "/image/avator/image-2.jpg",
    title: "Jack",
    callDuration: "35 Min Ago",
    callStatus: "Received",
    callTime: "05:45 PM",
  },
];
